data = [
    {
        "name": "Hackerspace OS"
        , "features": "Events, projects."
        , "license": "Open source, unknown."
        , "development": "Metalab fork is active, but focused on their local instance."
        , "stack": "Python, django."
        , "documentation": "None."
        , "installation": "Undocumented dependencies. Runtime errors on Ubuntu 14.04 LTS."
        , "usability": ""
        , "security": ""
        , "international": "Built-in through django. Strings in German."
        , "dataformat": ""
        , "api": ""
        , "auth": ""
        , "custom": ""
    },
    {
        "name": "GNU Cash"
        , "features": "Accounting, invoice."
        , "license": "Open source, GPL."
        , "development": "Last update: 2014-10-14"
        , "stack": "C, GTK+."
        , "documentation": "Manual, tutorial."
        , "installation": "No need to install."
        , "usability": ""
        , "security": "All data in unencrypted XML files; has backup"
        , "international": "English only."
        , "dataformat": "CSV"
        , "api": ""
        , "auth": ""
        , "custom": ""
    },
    {
        "name": "Schuel/Hmmm"
        , "features": "Events, rooms, recruiting hosts/mentors, discussion board."
        , "license": "Open source, WTFPL."
        , "development": "10 contributors, last commit: Nov. 7, 2014"
        , "stack": "meteor, mongodb"
        , "documentation": "README, installation instructions"
        , "installation": "through command line, fairly easy."
        , "usability": ""
        , "security": "Basic username / password login"
        , "international": "English, French, Italian, German."
        , "dataformat": ""
        , "api": ""
        , "auth": ""
        , "custom": ""
    },
    {
        "name": "Mematool"
        , "features": "Membership."
        , "license": "Open source, AGPL."
        , "development": "2 contributors"
        , "stack": "Python, sqlalchemy"
        , "documentation": "none."
        , "installation": "failed."
        , "usability": ""
        , "security": ""
        , "international": ""
        , "dataformat": ""
        , "api": ""
        , "auth": ""
        , "custom": ""
    },
    {
	"name": "Open Source Access Control Web Interface"
	, "features": ""
        , "license": "Creative Commons Attribution 3.0 license"
        , "development": "1 primary developer"
        , "stack": "Ruby (1.9.3, not the latest release, but required for Gemfiles), Rails 3, ImageMagick, arp-scan, PostgreSQL, Amazon S3 (or other storage for picture attachments), libq-dev, libsqlite3-dev"
        , "documentation": "Requires some prior knowledge of postgresql and Ruby on Rails"
        , "installation": "Succeeded with significant difficulty"
        , "usability": "Straightforward site design"
        , "security": "Ran Brakeman, which returned 34 security warnings, 14 with high confidence"
        , "international": ""
        , "dataformat": "postgresql or sqlite3"
        , "api": ""
        , "auth": ""
        , "custom": ""
    }
];
