data = [
    {
        "name": "Hackerspace OS"
        , "features": "Events, projects."
        , "license": "Open source, unknown."
        , "development": "Metalab fork is active, but focused on their local instance."
        , "stack": "Python, django."
        , "documentation": "None."
        , "installation": "Undocumented dependencies. Runtime errors on Ubuntu 14.04 LTS."
        , "usability": ""
        , "security": ""
        , "international": "Built-in through django. Strings in German."
        , "dataformat": ""
        , "api": ""
        , "auth": ""
        , "custom": ""
    },
    {
        "name": "GNU Cash"
        , "features": "Accounting, invoice."
        , "license": "Open source, GPL."
        , "development": "Last update: 2014-10-14"
        , "stack": "C, GTK+."
        , "documentation": "Manual, tutorial."
        , "installation": "No need to install."
        , "usability": ""
        , "security": "All data in unencrypted XML files; has backup"
        , "international": "English only."
        , "dataformat": "CSV"
        , "api": ""
        , "auth": ""
        , "custom": ""
    },
    {
        "name": "Schuel/Hmmm"
        , "features": "Events, rooms, recruiting hosts/mentors, discussion board."
        , "license": "Open source, WTFPL."
        , "development": "10 contributors, last commit: Nov. 7, 2014"
        , "stack": "meteor, mongodb"
        , "documentation": "README, installation instructions"
        , "installation": "through command line, fairly easy."
        , "usability": ""
        , "security": "Basic username / password login"
        , "international": "English, French, Italian, German."
        , "dataformat": ""
        , "api": ""
        , "auth": ""
        , "custom": ""
    },
    {
        "name": "Mematool"
        , "features": "Membership."
        , "license": "Open source, AGPL."
        , "development": "2 contributors"
        , "stack": "Python, sqlalchemy"
        , "documentation": "none."
        , "installation": "failed."
        , "usability": ""
        , "security": ""
        , "international": ""
        , "dataformat": ""
        , "api": ""
        , "auth": ""
        , "custom": ""
    }
];